name: Eleventy Build
on:
  push:
    branches:
    - eleventy
  pull_request:


jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@eleventy
    - name: Build
      uses: TartanLlama/actions-eleventy@v1.3
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/eleventy'
      with:
        publish_dir: _site
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
